### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by pepa65** [rofl0r/conpix#4]
Because this repo was 'discontinued', I started working with `concol`, but maybe just getting something smaller like this repo to use is easier..? In any case, after `./build.sh` I get:
```
In file included from ../NsNcurses.h:14,
                 from ../ConsoleWindow.h:15,
                 from ../ConsoleWindow.cpp:9:
../ConsoleWindow.cpp: In member function ‘void ConsoleWindow::getSize(int&, int&)’:
../ConsoleWindow.cpp:167:16: error: expected unqualified-id before ‘(’ token
  167 |   x = ncurses::getmaxx(ncurses::stdscr);
      |                ^~~~~~~
../ConsoleWindow.cpp:168:16: error: expected unqualified-id before ‘(’ token
  168 |   y = ncurses::getmaxy(ncurses::stdscr);
      |                ^~~~~~~
g++: error: ./ConsoleWindow.o: No such file or directory
mv: cannot stat 'a.out': No such file or directory
Finished building target: conpix
you can now run testt/conpix executable
```

**Comment by rofl0r** [comment]
i just tried, it compiles fine under ubuntu 20.04 using just `make`. maybe you need to set an older std such as `CXX="g++ -std=gnu++11" make`

**Comment by pepa65** [comment]
`CXX="g++ -std=gnu++11" make` gave more or less the same:
```
g++ -std=gnu++11 -O2 -g -Wall -fmessage-length=0   -c -o ConsoleWindow.o ConsoleWindow.cpp
In file included from NsNcurses.h:14,
                 from ConsoleWindow.h:15,
                 from ConsoleWindow.cpp:9:
ConsoleWindow.cpp: In member function ‘void ConsoleWindow::getSize(int&, int&)’:
ConsoleWindow.cpp:167:16: error: expected unqualified-id before ‘(’ token
  167 |   x = ncurses::getmaxx(ncurses::stdscr);
      |                ^~~~~~~
ConsoleWindow.cpp:168:16: error: expected unqualified-id before ‘(’ token
  168 |   y = ncurses::getmaxy(ncurses::stdscr);
      |                ^~~~~~~
make: *** [<builtin>: ConsoleWindow.o] Error 1
```
Am I missing some packages?? I think I have all the ncurses related dev packages.

**Comment by rofl0r** [comment]
i doubt this is due to missing packages, it's more likely that your ncurses version defines getmaxy and getmaxx as macros and this interferes with my "neat" C++ wrapper.... C++ being a pain in the ass is basically the reason i rewrote this as concol using the C language... you could try to suppress macro expansion by wrapping all occurences of "getmax[xy]" into parens like this `foo::(getmaxx)` by i don't know whether this works in C++ too.

**Comment by pepa65** [comment]
I put parentheses around `ncurses::getmaxx` and `ncurses::getmaxy` in `ConsoleWindow.cpp` and it all built, and works beautifully! Much better than img2txt too..!

**Comment by rofl0r** [comment]
cool. could you open a PR with your changes ?

**Comment by pepa65** [comment]
Glad you're still going to maintain it! I was already in the process of adopting it, so useful to have around, I am sure more people would like easy access to a utility like this.

Yes, the parentheses? I also found that "nowadays" the packages on Debian/Ubuntu that need to be installed are called: `libleptonica-dev libncurses5-dev libpng-dev libtiff-dev` (note the last two). Do you want that included as well?

**Comment by rofl0r** [comment]
> Yes, the parentheses?

correct.

> I also found that "nowadays" the packages on Debian/Ubuntu that need to be installed are called: libleptonica-dev libncurses5-dev libpng-dev libtiff-dev (note the last two).

the last 2 should be automatically pulled in by libleptonica-dev. also "nowadays" it should probably be "libncurses6-dev" instead of 5. pkg-config is now also required. if you want to update the documentation in this regard, please do so in a separate commit.

**Comment by pepa65** [comment]
Somehow there is no `libncurses6-dev`... I guess that is `libncurses-dev`. There is also a transitional package for `libncurses-dev`: `libtinfo-dev`. There is `libncurses6` and `libncursesw6`.

**Comment by rofl0r** [comment]
alright, thanks. i merged your updates, i guess this can be closed now.
